In [35]:
import pandas as pd
import matplotlib as plt
from sklearn.preprocessing import OneHotEncoder

In [36]:
df1 = pd.read_csv('Data/Resale Flat Prices (Based on Approval Date), 1990 - 1999.csv')
df2 = pd.read_csv('Data/Resale Flat Prices (Based on Approval Date), 2000 - Feb 2012.csv')
df3 = pd.read_csv('Data/Resale Flat Prices (Based on Registration Date), From Jan 2015 to Dec 2016.csv')
df4 = pd.read_csv('Data/Resale Flat Prices (Based on Registration Date), From Mar 2012 to Dec 2014.csv')
df5 = pd.read_csv('Data/Resale flat prices based on registration date from Jan-2017 onwards.csv')

In [37]:
print("df1",df1.shape)
print("df2",df2.shape)
print("df3",df3.shape)
print("df4",df4.shape)
print("df5",df5.shape)

df1 (287196, 10)
df2 (369651, 10)
df3 (37153, 11)
df4 (52203, 10)
df5 (223889, 11)

In [38]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 287196 entries, 0 to 287195
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   month                287196 non-null  str
 1   town                 287196 non-null  str
 2   flat_type            287196 non-null  str
 3   block                287196 non-null  str
 4   street_name          287196 non-null  str
 5   storey_range         287196 non-null  str
 6   floor_area_sqm       287196 non-null  float64
 7   flat_model           287196 non-null  str
 8   lease_commence_date  287196 non-null  int64
 9   resale_price         287196 non-null  int64
dtypes: float64(1), int64(2), str(7)
memory usage: 21.9 MB

In [39]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 37153 entries, 0 to 37152
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                37153 non-null  str
 1   town                 37153 non-null  str
 2   flat_type            37153 non-null  str
 3   block                37153 non-null  str
 4   street_name          37153 non-null  str
 5   storey_range         37153 non-null  str
 6   floor_area_sqm       37153 non-null  float64
 7   flat_model           37153 non-null  str
 8   lease_commence_date  37153 non-null  int64
 9   remaining_lease      37153 non-null  int64
 10  resale_price         37153 non-null  float64
dtypes: float64(2), int64(2), str(7)
memory usage: 3.1 MB

In [40]:
df3.drop(columns=['remaining_lease'],inplace=True)
df5.drop(columns=['remaining_lease'],inplace=True)

In [41]:
dfs = [df1,df2,df3,df4,df5]
df = pd.concat(dfs,ignore_index=True)

In [42]:
df.shape

(970092, 10)

In [43]:
df.tail()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price
970087,2026-01,YISHUN,EXECUTIVE,405,YISHUN AVE 6,04 TO 06,142.0,Apartment,1988,880000.0
970088,2026-01,YISHUN,EXECUTIVE,325,YISHUN CTRL,10 TO 12,146.0,Maisonette,1988,888000.0
970089,2026-01,YISHUN,EXECUTIVE,325,YISHUN CTRL,04 TO 06,146.0,Maisonette,1988,920000.0
970090,2026-01,YISHUN,EXECUTIVE,360,YISHUN RING RD,07 TO 09,142.0,Apartment,1988,865888.0
970091,2026-01,YISHUN,EXECUTIVE,643,YISHUN ST 61,10 TO 12,142.0,Apartment,1987,825000.0

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 970092 entries, 0 to 970091
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   month                970092 non-null  str
 1   town                 970092 non-null  str
 2   flat_type            970092 non-null  str
 3   block                970092 non-null  str
 4   street_name          970092 non-null  str
 5   storey_range         970092 non-null  str
 6   floor_area_sqm       970092 non-null  float64
 7   flat_model           970092 non-null  str
 8   lease_commence_date  970092 non-null  int64
 9   resale_price         970092 non-null  float64
dtypes: float64(2), int64(1), str(7)
memory usage: 74.0 MB

In [45]:
df = df.drop_duplicates()

In [46]:
df['year'] = [int(i[0]) for i in df.month.str.split('-')]
df['mon'] = [int(i[1]) for i in df.month.str.split('-')]

In [47]:
df.drop(columns=['month'],inplace=True)

In [48]:
print('Town column unique values:',df.town.nunique())
print('Flat type column unique values:',df.flat_type.nunique())
print('Block column unique values:',df.block.nunique())
print('street_name column unique values:',df.street_name.nunique())
print('storey_range column unique values:',df.storey_range.nunique())
print('flat_model column unique values:',df.flat_model.nunique())

Town column unique values: 27
Flat type column unique values: 8
Block column unique values: 2751
street_name column unique values: 594
storey_range column unique values: 25
flat_model column unique values: 34

In [49]:
df.flat_type = df.flat_type.replace('MULTI GENERATION','MULTI-GENERATION')

In [50]:
df.info()

<class 'pandas.DataFrame'>
Index: 968087 entries, 0 to 970091
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   town                 968087 non-null  str
 1   flat_type            968087 non-null  str
 2   block                968087 non-null  str
 3   street_name          968087 non-null  str
 4   storey_range         968087 non-null  str
 5   floor_area_sqm       968087 non-null  float64
 6   flat_model           968087 non-null  str
 7   lease_commence_date  968087 non-null  int64
 8   resale_price         968087 non-null  float64
 9   year                 968087 non-null  int64
 10  mon                  968087 non-null  int64
dtypes: float64(2), int64(3), str(6)
memory usage: 88.6 MB

In [51]:
dff = df

In [52]:
df['storey_mid'] = df['storey_range'].str.extract(r'(\d+)').astype(int)

In [55]:
dff

,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,year,mon,storey_mid
0,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,9000.0,1990,1,10
1,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,04 TO 06,31.0,IMPROVED,1977,6000.0,1990,1,4
2,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,8000.0,1990,1,10
3,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,07 TO 09,31.0,IMPROVED,1977,6000.0,1990,1,7
4,ANG MO KIO,3 ROOM,216,ANG MO KIO AVE 1,04 TO 06,73.0,NEW GENERATION,1976,47200.0,1990,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...
970087,YISHUN,EXECUTIVE,405,YISHUN AVE 6,04 TO 06,142.0,Apartment,1988,880000.0,2026,1,4
970088,YISHUN,EXECUTIVE,325,YISHUN CTRL,10 TO 12,146.0,Maisonette,1988,888000.0,2026,1,10
970089,YISHUN,EXECUTIVE,325,YISHUN CTRL,04 TO 06,146.0,Maisonette,1988,920000.0,2026,1,4
970090,YISHUN,EXECUTIVE,360,YISHUN RING RD,07 TO 09,142.0,Apartment,1988,865888.0,2026,1,7
970091,YISHUN,EXECUTIVE,643,YISHUN ST 61,10 TO 12,142.0,Apartment,1987,825000.0,2026,1,10

In [23]:
ohe = OneHotEncoder(handle_unknown='ignore',sparse_output=False)
town_encoded = ohe.fit_transform(df[['town']])

In [24]:
town_df = pd.DataFrame(town_encoded, columns=ohe.get_feature_names_out(['town']))

In [27]:
df = pd.concat([df.drop(columns=['town']).reset_index(drop=True), town_df.reset_index(drop=True)], axis=1 )

In [28]:
ct = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(), ['town', 'flat_type'])
], remainder='passthrough')

In [29]:
X = ct.fit_transform(df)

ValueError: A given column is not a column of the dataframe

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor

# Categorical low-cardinality
cat_cols = ['town', 'flat_type', 'flat_model']

# Numeric columns
num_cols = ['floor_area_sqm', 'lease_commence_date', 'resale_price','year','mon','storey_mid']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler())
        ]), num_cols)
    ],
    remainder='drop'
)

model = Pipeline([
    ('preprocess', preprocessor),
    ('regressor', RandomForestRegressor())
])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

NameError: name 'X_train' is not defined