In [1]:
import pandas as pd
import matplotlib as plt

In [2]:
df1 = pd.read_csv('Data/Resale Flat Prices (Based on Approval Date), 1990 - 1999.csv')
df2 = pd.read_csv('Data/Resale Flat Prices (Based on Approval Date), 2000 - Feb 2012.csv')
df3 = pd.read_csv('Data/Resale Flat Prices (Based on Registration Date), From Jan 2015 to Dec 2016.csv')
df4 = pd.read_csv('Data/Resale Flat Prices (Based on Registration Date), From Mar 2012 to Dec 2014.csv')
df5 = pd.read_csv('Data/Resale flat prices based on registration date from Jan-2017 onwards.csv')

In [24]:
pip list

Package                   Version
------------------------- -----------
anyio                     4.12.1
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.1.0
attrs                     25.4.0
babel                     2.17.0
beautifulsoup4            4.14.3
bleach                    6.3.0
certifi                   2026.1.4
cffi                      2.0.0
charset-normalizer        3.4.4
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.3.3
cycler                    0.12.1
debugpy                   1.8.19
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.21.2
fonttools                 4.61.1
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel                 7.1.0
ipython                   9.9.0
ipython_pygments_lexers   1.1.1
ipywidgets                8.1.8
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.6
json5                     0.13.0
jsonpointer               3.0.0
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupyter                   1.1.1
jupyter_client            8.8.0
jupyter-console           6.6.3
jupyter_core              5.9.1
jupyter-events            0.12.0
jupyter-lsp               2.3.0
jupyter_server            2.17.0
jupyter_server_terminals  0.5.4
jupyterlab                4.5.3
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
jupyterlab_widgets        3.0.16
kiwisolver                1.4.9
lab                       8.8
lark                      1.3.1
MarkupSafe                3.0.3
matplotlib                3.10.8
matplotlib-inline         0.2.1
mistune                   3.2.0
nbclient                  0.10.4
nbconvert                 7.16.6
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook                  7.5.2
notebook_shim             0.2.4
numpy                     2.4.1
packaging                 26.0
pandas                    3.0.0
pandocfilters             1.5.1
parso                     0.8.5
pillow                    12.1.0
pip                       25.3
platformdirs              4.5.1
prometheus_client         0.24.1
prompt_toolkit            3.0.52
psutil                    7.2.1
pure_eval                 0.2.3
pycparser                 3.0
Pygments                  2.19.2
pyparsing                 3.3.2
python-dateutil           2.9.0.post0
python-json-logger        4.0.0
pywinpty                  3.0.2
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
requests                  2.32.5
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   0.30.0
Send2Trash                2.1.0
setuptools                80.10.1
simplejson                3.20.2
six                       1.17.0
soupsieve                 2.8.3
stack-data                0.6.3
terminado                 0.18.1
tinycss2                  1.4.0
tornado                   6.5.4
traitlets                 5.14.3
txt2tags                  3.9
typing_extensions         4.15.0
tzdata                    2025.3
uri-template              1.3.0
urllib3                   2.6.3
wcwidth                   0.3.2
webcolors                 25.10.0
webencodings              0.5.1
websocket-client          1.9.0
widgetsnbextension        4.0.15
Note: you may need to restart the kernel to use updated packages.

In [3]:
print("df1",df1.shape)
print("df2",df2.shape)
print("df3",df3.shape)
print("df4",df4.shape)
print("df5",df5.shape)

df1 (287196, 10)
df2 (369651, 10)
df3 (37153, 11)
df4 (52203, 10)
df5 (223889, 11)

In [5]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 287196 entries, 0 to 287195
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   month                287196 non-null  str
 1   town                 287196 non-null  str
 2   flat_type            287196 non-null  str
 3   block                287196 non-null  str
 4   street_name          287196 non-null  str
 5   storey_range         287196 non-null  str
 6   floor_area_sqm       287196 non-null  float64
 7   flat_model           287196 non-null  str
 8   lease_commence_date  287196 non-null  int64
 9   resale_price         287196 non-null  int64
dtypes: float64(1), int64(2), str(7)
memory usage: 21.9 MB

In [6]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 37153 entries, 0 to 37152
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                37153 non-null  str
 1   town                 37153 non-null  str
 2   flat_type            37153 non-null  str
 3   block                37153 non-null  str
 4   street_name          37153 non-null  str
 5   storey_range         37153 non-null  str
 6   floor_area_sqm       37153 non-null  float64
 7   flat_model           37153 non-null  str
 8   lease_commence_date  37153 non-null  int64
 9   remaining_lease      37153 non-null  int64
 10  resale_price         37153 non-null  float64
dtypes: float64(2), int64(2), str(7)
memory usage: 3.1 MB

In [7]:
df3.drop(columns=['remaining_lease'],inplace=True)
df5.drop(columns=['remaining_lease'],inplace=True)

In [8]:
dfs = [df1,df2,df3,df4,df5]
df = pd.concat(dfs,ignore_index=True)

In [9]:
df.shape

(970092, 10)

In [10]:
df.tail()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price
970087,2026-01,YISHUN,EXECUTIVE,405,YISHUN AVE 6,04 TO 06,142.0,Apartment,1988,880000.0
970088,2026-01,YISHUN,EXECUTIVE,325,YISHUN CTRL,10 TO 12,146.0,Maisonette,1988,888000.0
970089,2026-01,YISHUN,EXECUTIVE,325,YISHUN CTRL,04 TO 06,146.0,Maisonette,1988,920000.0
970090,2026-01,YISHUN,EXECUTIVE,360,YISHUN RING RD,07 TO 09,142.0,Apartment,1988,865888.0
970091,2026-01,YISHUN,EXECUTIVE,643,YISHUN ST 61,10 TO 12,142.0,Apartment,1987,825000.0

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 970092 entries, 0 to 970091
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   month                970092 non-null  str
 1   town                 970092 non-null  str
 2   flat_type            970092 non-null  str
 3   block                970092 non-null  str
 4   street_name          970092 non-null  str
 5   storey_range         970092 non-null  str
 6   floor_area_sqm       970092 non-null  float64
 7   flat_model           970092 non-null  str
 8   lease_commence_date  970092 non-null  int64
 9   resale_price         970092 non-null  float64
dtypes: float64(2), int64(1), str(7)
memory usage: 74.0 MB

In [12]:
df = df.drop_duplicates()

In [13]:
df['year'] = [int(i[0]) for i in df.month.str.split('-')]
df['mon'] = [int(i[1]) for i in df.month.str.split('-')]

In [14]:
df.block.unique()

<StringArray>
[ '309',  '216',  '211',  '202',  '235',  '232',  '308',  '220',  '219',
  '247',
 ...
 '875B', '479A', '478B', '478C', '478A', '479B', '479C', '421A', '409D',
 '876C']
Length: 2751, dtype: str

In [15]:
df.flat_type = df.flat_type.replace('MULTI GENERATION','MULTI-GENERATION')

In [16]:
df.describe()

,floor_area_sqm,lease_commence_date,resale_price,year,mon
count,968087.000000,968087.000000,9.680870e+05,968087.000000,968087.000000
mean,95.686591,1988.723358,3.351393e+05,2006.991561,6.571610
std,25.741439,11.097338,1.841878e+05,9.874719,3.411916
min,28.000000,1966.000000,5.000000e+03,1990.000000,1.000000
25%,73.000000,1981.000000,1.990000e+05,1999.000000,4.000000
50%,93.000000,1986.000000,3.070000e+05,2006.000000,7.000000
75%,113.000000,1996.000000,4.340000e+05,2016.000000,10.000000
max,366.700000,2021.000000,1.658888e+06,2026.000000,12.000000

In [18]:
df.corr

<bound method DataFrame.corr of           month        town  flat_type block       street_name storey_range  \
0       1990-01  ANG MO KIO     1 ROOM   309  ANG MO KIO AVE 1     10 TO 12
1       1990-01  ANG MO KIO     1 ROOM   309  ANG MO KIO AVE 1     04 TO 06
2       1990-01  ANG MO KIO     1 ROOM   309  ANG MO KIO AVE 1     10 TO 12
3       1990-01  ANG MO KIO     1 ROOM   309  ANG MO KIO AVE 1     07 TO 09
4       1990-01  ANG MO KIO     3 ROOM   216  ANG MO KIO AVE 1     04 TO 06
...         ...         ...        ...   ...               ...          ...
970087  2026-01      YISHUN  EXECUTIVE   405      YISHUN AVE 6     04 TO 06
970088  2026-01      YISHUN  EXECUTIVE   325       YISHUN CTRL     10 TO 12
970089  2026-01      YISHUN  EXECUTIVE   325       YISHUN CTRL     04 TO 06
970090  2026-01      YISHUN  EXECUTIVE   360    YISHUN RING RD     07 TO 09
970091  2026-01      YISHUN  EXECUTIVE   643      YISHUN ST 61     10 TO 12

        floor_area_sqm      flat_model  lease_commence_date  resale_price  \
0                 31.0        IMPROVED                 1977        9000.0
1                 31.0        IMPROVED                 1977        6000.0
2                 31.0        IMPROVED                 1977        8000.0
3                 31.0        IMPROVED                 1977        6000.0
4                 73.0  NEW GENERATION                 1976       47200.0
...                ...             ...                  ...           ...
970087           142.0       Apartment                 1988      880000.0
970088           146.0      Maisonette                 1988      888000.0
970089           146.0      Maisonette                 1988      920000.0
970090           142.0       Apartment                 1988      865888.0
970091           142.0       Apartment                 1987      825000.0

        year  mon
0       1990    1
1       1990    1
2       1990    1
3       1990    1
4       1990    1
...      ...  ...
970087  2026    1
970088  2026    1
970089  2026    1
970090  2026    1
970091  2026    1

[968087 rows x 12 columns]>