In [1]:
import pandas as pd
import matplotlib as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor

In [2]:
df1 = pd.read_csv('Data/Resale Flat Prices (Based on Approval Date), 1990 - 1999.csv')
df2 = pd.read_csv('Data/Resale Flat Prices (Based on Approval Date), 2000 - Feb 2012.csv')
df3 = pd.read_csv('Data/Resale Flat Prices (Based on Registration Date), From Jan 2015 to Dec 2016.csv')
df4 = pd.read_csv('Data/Resale Flat Prices (Based on Registration Date), From Mar 2012 to Dec 2014.csv')
df5 = pd.read_csv('Data/Resale flat prices based on registration date from Jan-2017 onwards.csv')

In [3]:
print("df1",df1.shape)
print("df2",df2.shape)
print("df3",df3.shape)
print("df4",df4.shape)
print("df5",df5.shape)

df1 (287196, 10)
df2 (369651, 10)
df3 (37153, 11)
df4 (52203, 10)
df5 (223889, 11)

In [4]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 287196 entries, 0 to 287195
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   month                287196 non-null  str
 1   town                 287196 non-null  str
 2   flat_type            287196 non-null  str
 3   block                287196 non-null  str
 4   street_name          287196 non-null  str
 5   storey_range         287196 non-null  str
 6   floor_area_sqm       287196 non-null  float64
 7   flat_model           287196 non-null  str
 8   lease_commence_date  287196 non-null  int64
 9   resale_price         287196 non-null  int64
dtypes: float64(1), int64(2), str(7)
memory usage: 21.9 MB

In [5]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 37153 entries, 0 to 37152
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                37153 non-null  str
 1   town                 37153 non-null  str
 2   flat_type            37153 non-null  str
 3   block                37153 non-null  str
 4   street_name          37153 non-null  str
 5   storey_range         37153 non-null  str
 6   floor_area_sqm       37153 non-null  float64
 7   flat_model           37153 non-null  str
 8   lease_commence_date  37153 non-null  int64
 9   remaining_lease      37153 non-null  int64
 10  resale_price         37153 non-null  float64
dtypes: float64(2), int64(2), str(7)
memory usage: 3.1 MB

In [6]:
df3.drop(columns=['remaining_lease'],inplace=True)
df5.drop(columns=['remaining_lease'],inplace=True)

In [7]:
dfs = [df1,df2,df3,df4,df5]
df = pd.concat(dfs,ignore_index=True)

In [8]:
df.shape

(970092, 10)

In [9]:
df.tail()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price
970087,2026-01,YISHUN,EXECUTIVE,405,YISHUN AVE 6,04 TO 06,142.0,Apartment,1988,880000.0
970088,2026-01,YISHUN,EXECUTIVE,325,YISHUN CTRL,10 TO 12,146.0,Maisonette,1988,888000.0
970089,2026-01,YISHUN,EXECUTIVE,325,YISHUN CTRL,04 TO 06,146.0,Maisonette,1988,920000.0
970090,2026-01,YISHUN,EXECUTIVE,360,YISHUN RING RD,07 TO 09,142.0,Apartment,1988,865888.0
970091,2026-01,YISHUN,EXECUTIVE,643,YISHUN ST 61,10 TO 12,142.0,Apartment,1987,825000.0

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 970092 entries, 0 to 970091
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   month                970092 non-null  str
 1   town                 970092 non-null  str
 2   flat_type            970092 non-null  str
 3   block                970092 non-null  str
 4   street_name          970092 non-null  str
 5   storey_range         970092 non-null  str
 6   floor_area_sqm       970092 non-null  float64
 7   flat_model           970092 non-null  str
 8   lease_commence_date  970092 non-null  int64
 9   resale_price         970092 non-null  float64
dtypes: float64(2), int64(1), str(7)
memory usage: 74.0 MB

In [11]:
df = df.drop_duplicates()

In [12]:
df['year'] = [int(i[0]) for i in df.month.str.split('-')]
df['mon'] = [int(i[1]) for i in df.month.str.split('-')]

In [13]:
df.drop(columns=['month'],inplace=True)

In [35]:
print('Town column unique values:',df.town.nunique())
print('Flat type column unique values:',df.flat_type.nunique())
print('Block column unique values:',df.block.nunique())
print('street_name column unique values:',df.street_name.nunique())
print('storey_range column unique values:',df.storey_range.nunique())
print('flat_model column unique values:',df.flat_model.nunique())

AttributeError: 'DataFrame' object has no attribute 'town'

In [15]:
df.flat_type = df.flat_type.replace('MULTI GENERATION','MULTI-GENERATION')

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 968087 entries, 0 to 968086
Data columns (total 44 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   block                       968087 non-null  str
 1   street_name                 968087 non-null  str
 2   storey_range                968087 non-null  str
 3   floor_area_sqm              968087 non-null  float64
 4   flat_model                  968087 non-null  str
 5   lease_commence_date         968087 non-null  int64
 6   resale_price                968087 non-null  float64
 7   year                        968087 non-null  int64
 8   mon                         968087 non-null  int64
 9   storey_mid                  968087 non-null  int64
 10  town_ANG MO KIO             968087 non-null  float64
 11  town_BEDOK                  968087 non-null  float64
 12  town_BISHAN                 968087 non-null  float64
 13  town_BUKIT BATOK            968087 non-null  float64
 14  town_BUKIT MERAH            968087 non-null  float64
 15  town_BUKIT PANJANG          968087 non-null  float64
 16  town_BUKIT TIMAH            968087 non-null  float64
 17  town_CENTRAL AREA           968087 non-null  float64
 18  town_CHOA CHU KANG          968087 non-null  float64
 19  town_CLEMENTI               968087 non-null  float64
 20  town_GEYLANG                968087 non-null  float64
 21  town_HOUGANG                968087 non-null  float64
 22  town_JURONG EAST            968087 non-null  float64
 23  town_JURONG WEST            968087 non-null  float64
 24  town_KALLANG/WHAMPOA        968087 non-null  float64
 25  town_LIM CHU KANG           968087 non-null  float64
 26  town_MARINE PARADE          968087 non-null  float64
 27  town_PASIR RIS              968087 non-null  float64
 28  town_PUNGGOL                968087 non-null  float64
 29  town_QUEENSTOWN             968087 non-null  float64
 30  town_SEMBAWANG              968087 non-null  float64
 31  town_SENGKANG               968087 non-null  float64
 32  town_SERANGOON              968087 non-null  float64
 33  town_TAMPINES               968087 non-null  float64
 34  town_TOA PAYOH              968087 non-null  float64
 35  town_WOODLANDS              968087 non-null  float64
 36  town_YISHUN                 968087 non-null  float64
 37  flat_type_1 ROOM            968087 non-null  float64
 38  flat_type_2 ROOM            968087 non-null  float64
 39  flat_type_3 ROOM            968087 non-null  float64
 40  flat_type_4 ROOM            968087 non-null  float64
 41  flat_type_5 ROOM            968087 non-null  float64
 42  flat_type_EXECUTIVE         968087 non-null  float64
 43  flat_type_MULTI-GENERATION  968087 non-null  float64
dtypes: float64(36), int64(4), str(4)
memory usage: 325.0 MB

In [18]:
df['storey_mid'] = df['storey_range'].str.extract(r'(\d+)').astype(int)

In [20]:
ohe = OneHotEncoder(handle_unknown='ignore',sparse_output=False)
town_encoded = ohe.fit_transform(df[['town']])

In [21]:
town_df = pd.DataFrame(town_encoded, columns=ohe.get_feature_names_out(['town']))

In [22]:
df = pd.concat([df.drop(columns=['town']).reset_index(drop=True), town_df.reset_index(drop=True)], axis=1 )

In [27]:
flat_encoded = ohe.fit_transform(df[['flat_type']])

In [32]:
flat_df = pd.DataFrame(flat_encoded, columns=ohe.get_feature_names_out(['flat_type']))
df = pd.concat([df.drop(columns=['flat_type']).reset_index(drop=True), flat_df.reset_index(drop=True)], axis=1 )

In [33]:
df.head()

,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,year,mon,storey_mid,...,town_TOA PAYOH,town_WOODLANDS,town_YISHUN,flat_type_1 ROOM,flat_type_2 ROOM,flat_type_3 ROOM,flat_type_4 ROOM,flat_type_5 ROOM,flat_type_EXECUTIVE,flat_type_MULTI-GENERATION
0,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,9000.0,1990,1,10,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,309,ANG MO KIO AVE 1,04 TO 06,31.0,IMPROVED,1977,6000.0,1990,1,4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,8000.0,1990,1,10,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,309,ANG MO KIO AVE 1,07 TO 09,31.0,IMPROVED,1977,6000.0,1990,1,7,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,216,ANG MO KIO AVE 1,04 TO 06,73.0,NEW GENERATION,1976,47200.0,1990,1,4,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [41]:
print('Block column unique values:',df.block.nunique())
print('street_name column unique values:',df.street_name.nunique())
print('storey_range column unique values:',df.storey_range.nunique())
print('flat_model column unique values:',df.flat_model.nunique())

Block column unique values: 2751
street_name column unique values: 594
storey_range column unique values: 25
flat_model column unique values: 34

In [42]:
block_freq = df.block.value_counts()

In [47]:
df['block_freq'] = df['block'].map(block_freq)
df.drop(columns=['block'], inplace=True)

In [48]:
import joblib
joblib.dump(block_freq, "block_freq.pkl")

,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,year,mon,storey_mid,town_ANG MO KIO,...,town_WOODLANDS,town_YISHUN,flat_type_1 ROOM,flat_type_2 ROOM,flat_type_3 ROOM,flat_type_4 ROOM,flat_type_5 ROOM,flat_type_EXECUTIVE,flat_type_MULTI-GENERATION,block_freq
0,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,9000.0,1990,1,10,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1468
1,ANG MO KIO AVE 1,04 TO 06,31.0,IMPROVED,1977,6000.0,1990,1,4,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1468
2,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,8000.0,1990,1,10,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1468
3,ANG MO KIO AVE 1,07 TO 09,31.0,IMPROVED,1977,6000.0,1990,1,7,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1468
4,ANG MO KIO AVE 1,04 TO 06,73.0,NEW GENERATION,1976,47200.0,1990,1,4,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1611

In [49]:
street_freq = df['street_name'].value_counts()

# map frequency
df['street_freq'] = df['street_name'].map(street_freq)

# drop original column
df.drop(columns=['street_name'], inplace=True)

In [51]:
import joblib
joblib.dump(street_freq,"street_freq.pkl")

['street_freq.pkl']

In [56]:
df.flat_model.unique()

<StringArray>
[              'IMPROVED',         'NEW GENERATION',                'MODEL A',
               'STANDARD',             'SIMPLIFIED',     'MODEL A-MAISONETTE',
              'APARTMENT',             'MAISONETTE',                'TERRACE',
                 '2-ROOM',    'IMPROVED-MAISONETTE',       'MULTI GENERATION',
      'PREMIUM APARTMENT',               'Improved',         'New Generation',
                'Model A',               'Standard',              'Apartment',
             'Simplified',     'Model A-Maisonette',             'Maisonette',
       'Multi Generation',          'Adjoined flat',      'Premium Apartment',
                'Terrace',    'Improved-Maisonette',     'Premium Maisonette',
                 '2-room',               'Model A2',                'Type S1',
                'Type S2',                   'DBSS', 'Premium Apartment Loft',
                   '3Gen']
Length: 34, dtype: str

In [ ]:
flat_model_encoded = ohe.fit_transform(df[['flat_model']])

flat_model_df = pd.DataFrame(
    flat_model_encoded,
    columns=ohe.get_feature_names_out(['flat_model'])
)

df = pd.concat([df.drop(columns=['flat_model']).reset_index(drop=True),
                flat_model_df.reset_index(drop=True)], axis=1)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor

# Categorical low-cardinality
cat_cols = ['town', 'flat_type', 'flat_model']

# Numeric columns
num_cols = ['floor_area_sqm', 'lease_commence_date', 'resale_price','year','mon','storey_mid']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler())
        ]), num_cols)
    ],
    remainder='drop'
)

model = Pipeline([
    ('preprocess', preprocessor),
    ('regressor', RandomForestRegressor())
])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)